authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
    path('add/', views.add_author, name='add_author'),
    path('<int:pk>/', views.author_detail, name='author_detail'),
    path('', views.author_list, name='author_list'),
    path('authors/', views.author_list, name='author_list')
]

noteapp/urls.py
from django.urls import path, include
from . import views

app_name = 'noteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('tag/', views.tag, name='tag'),
    path('note/', views.note, name='note'),
    path('detail/<int:note_id>', views.detail, name='detail'),
    path('done/<int:note_id>', views.set_done, name='set_done'),
    path('delete/<int:note_id>', views.delete_note, name='delete'),
    path('add-author/', views.add_author, name='add_author'),
    path('<int:pk>/', views.author_detail, name='author_detail'),
    path('authors/', include('authors.urls')),
    path('authors/', views.author_list, name='author_list'),
    # path('list/', views.list_view, name='list'),
    
]

notes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('noteapp.urls')),
    path('users/', include('users.urls')),
    path('authors/', include('authors.urls')),
    path('quotes/', include('quotes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/urls.py
from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns = [
    path('add/', views.add_quote, name='add_quote'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile')
]

noteapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=25, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'name'], name='tag of username')
        ]

    def __str__(self):
        return f"{self.name}"


class Note(models.Model):
    name = models.CharField(max_length=50, null=False)
    description = models.CharField(max_length=150, null=False)
    done = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.name}"
    
class Author(models.Model):
    name = models.CharField(max_length=100)
    bio = models.TextField(blank=True)

    def __str__(self):
        return self.name

noteapp/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Tag, Note, Author  
from django import forms


class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']

class NoteForm(ModelForm):

    name = CharField(min_length=5, max_length=50, required=True, widget=TextInput())
    description = CharField(min_length=10, max_length=150, required=True, widget=TextInput())

    class Meta:
        model = Note
        fields = ['name', 'description']
        exclude = ['tags']
        # widgets = {'tags': format.CheckboxSelectMultiple}

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['name']

noteapp/templates/noteapp/views.py
from django.shortcuts import render
# from django.http import HttpResponse

# Create your views here.
def main(request):
    return render(request, 'noteapp/index.html')


# def main(request):
#     return HttpResponse("Hello, world!")

noteapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import TagForm, NoteForm, AuthorForm
from .models import Tag, Note, Author
from django.contrib import messages
from quotes.models import Quote


# Create your views here.
@login_required
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            tag.user = request.user
            tag.save()
            messages.success(request, 'Tag added successfully!')
            return redirect(to='noteapp:main')
        else:
            messages.error(request, 'Form is not valid.')
            return render(request, 'noteapp/tag.html', {'form': form})

    return render(request, 'noteapp/tag.html', {'form': TagForm()})

@login_required
def note(request):
    tags = Tag.objects.filter(user=request.user).all()

    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            new_note.user = request.user
            new_note.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'), user=request.user)
            for tag in choice_tags.iterator():
                new_note.tags.add(tag)

            return redirect(to='noteapp:main')
        else:
            return render(request, 'noteapp/note.html', {"tags": tags, 'form': form})

    return render(request, 'noteapp/note.html', {"tags": tags, 'form': NoteForm()})


@login_required
def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('authors_list') 
    else:
        form = AuthorForm()
    return render(request, 'noteapp/add_author.html', {'form': form})

def author_list(request):
    authors = Author.objects.all()
    return render(request, 'noteapp/author_list.html', {'authors': authors})

def author_detail(request, pk):
    author = get_object_or_404(Author, pk=pk)
    return render(request, 'noteapp/author_detail.html', {'author': author})

@login_required
def detail(request, note_id):
    note = get_object_or_404(Note, pk=note_id, user=request.user)
    return render(request, 'noteapp/detail.html', {"note": note})

@login_required
def set_done(request, note_id):
    Note.objects.filter(pk=note_id, user=request.users).update(done=True)
    return redirect(to='noteapp:main')

@login_required
def delete_note(request, note_id):
    Note.objects.get(pk=note_id, user=request.user).delete()
    return redirect(to='noteapp:main')


def main(request):
    notes = Note.objects.filter(user=request.user).all() if request.user.is_authenticated else []
    quotes = Quote.objects.all()
    return render(request, 'noteapp/index.html', {"notes": notes, "quotes": quotes})

noteapp/templates/noteapp/add_author.html
{% extends "base.html" %}

{% block content %}
  <h2>Add New Author</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Author</button>
  </form>
{% endblock %}

noteapp/templates/noteapp/author_detail.html
<!-- templates/authors/author_detail.html -->
{% extends "base_generic.html" %}

{% block content %}
  <h2>{{ author.name }}</h2>
  <p>{{ author.bio }}</p>
{% endblock %}

noteapp/templates/noteapp/author_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Author List</title>
</head>
<body>
    <h1>Authors</h1>
    <ul>
        {% for author in authors %}
            <li><a href="{% url 'author_detail' author.pk %}">{{ author.name }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

noteapp/templates/noteapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'noteapp/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Go back to the main page </a></li>
        </ul>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

noteapp/templates/noteapp/detail.html
{% extends "noteapp/base.html" %} {% load extract_tags %} {% block content %}

<h1>{{note.name}}</h1>
<p>Description: <b>{{note.description}}</b></p>
<p>Time of creation: <kbd>{{note.created}}</kbd></p>
{% if note.done %}
<p>
  Status:
  <ins>Completed</ins>
</p>
{% else %}
<p>Status: <i>Not implemented</i></p>
{% endif %}
<p>Tags: <small> {{ note.tags|tags }} </small></p>
{% endblock %}

noteapp/templates/noteapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Organizer</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        {% if user.is_authenticated %}
        <ul>
            <li><a href="{% url 'noteapp:note' %}" role="button">Add note</a></li>
            <li><a href="{% url 'noteapp:tag' %}" role="button">Add Tag</a></li>
            <li><a href="{% url 'authors:author_list' %}" role="button">Authors</a></li> 
            <li><a href="{% url 'authors:add_author' %}" role="button">Add Author</a></li>
            <li><a href="{% url 'quotes:add_quote' %}" role="button">Add Quote</a></li>
        </ul>
        <ul>
            <li>Welcome <b>{{ user.username }}!</b></li>
            <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>
            <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
        </ul>
        {% else %}
        <ul>
            <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
            <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
        </ul>
        {% endif %}
    </nav>

    {% for note in notes %}
    <ul>
        <li>
            {% if not note.done %}
            <a href="{% url 'noteapp:detail' note.id %}" role="button" class="outline"> {{ note.name }} </a>
            <a href="{% url 'noteapp:set_done' note.id %}" role="button"> Mark Done </a>
            <a href="{% url 'noteapp:delete' note.id %}" role="button" class="contrast"> Delete note </a>
            {% else %}
            <a href="{% url 'noteapp:detail' note.id %}" role="button" class="secondary"><s>{{ note.name }}</s></a>
            {% endif %}
        </li>
    </ul>
    {% endfor %}
    <section>
        <h2>Quotes</h2>
        {% for quote in quotes %}
        <ul>
            <li>{{ quote.text }} - {{ quote.author }}</li>
        </ul>
        {% endfor %}
    </section>
</main>
</body>
</html>

noteapp/templates/noteapp/note.html
{% extends "noteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'noteapp:note' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Note name:
            {{ form.name }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label> Note description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

noteapp/templates/noteapp/tag.html
{% extends "noteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'noteapp:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}