notes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('noteapp.urls')),
    path('users/', include('users.urls')),
    path('authors/', include('authors.urls')),
    path('quotes/', include('quotes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/urls.py
from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns = [
    path('add/', views.add_quote, name='add_quote'),
]

quotes/models.py
from django.db import models
from django.conf import settings
from authors.models import Author

class Author(models.Model):
    name = models.CharField(max_length=255)
    bio = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

class Quote(models.Model):
    text = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='quotes')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author}'

quotes/forms.py
from django import forms
from .models import Quote
from authors.models import Author

class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['text', 'author']  # Поля, которые включены в форму
        widgets = {
            'author': forms.Select(),
        }
    
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['author'].queryset = Author.objects.all()

quotes/views.py
from django.shortcuts import render, redirect
from .forms import QuoteForm
from .models import Quote
from django.http import HttpResponse
from noteapp.models import Note
from authors.models import Author


def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            quote = form.save(commit=False)
            quote.user = request.user
            quote.save()
            return redirect('noteapp:main')
    else:
        form = QuoteForm()

    return render(request, 'quotes/add_quote.html', {'form': form})

def index(request):
    notes = Note.objects.all()
    quotes = Quote.objects.all()  # Получение всех цитат из базы данных
    return render(request, 'index.html', {'quotes': quotes})

quotes/templates/quotes/add_quote.html
{% extends "noteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote text:
            {{ form.text }}
        </label>
        <span>{{ form.errors.text }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select author:
            <select name="author" id="id_author">
                {% for author in form.author.field.queryset %}
                    <option value="{{ author.id }}">{{ author.name }}</option>
                {% endfor %}
            </select>
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}